### PR TITLE
fix: from-map rule is not working on TS files

### LINKED ISSUE #49: [from-map] Does not work with TS files
#### Config
```json
{
  "parserOptions": {
    "sourceType": "module"
  },
  "parser": "@typescript-eslint/parser",
  "plugins": ["array-func"],
  "rules": {
    "array-func/from-map": "error"
  }
}
```

#### Code 
```ts
Array.from({length: 5 }).map((x) => x);
```

#### Expected behavior
Should fix correctly as following:

```ts
Array.from({length: 5 }, (x) => x);
```

#### Actual behavior
Fixes incorrect:
```ts
, Array.from({length: 5 }).map((x) => x);
```

Here is repo: https://github.com/doniyor2109/demo-error-for-array-func-from-map

### PR DESCRIPTION
**Pull request by doniyor2109**
Fixes  #49

### CODE REVIEW

**Comment by freaktechnik** [comment]
Hm, if the location info is indeed the issue I fear most rules won't behave properly with the TS parser.

**Comment by freaktechnik** [comment]
More importantly: thank you very much for the PR, I'll try to get to it within a week or so.

**Comment by doniyor2109** [comment]
We have big codebase using Typescript and only this rule is broken at the moment

File: rules/from-map.js [hunk 1]
```diff
@@ -76,18 +76,18 @@ module.exports = {
                             }
                             // The original map callback from Array.from gets nested as a parameter to the callback from map.
                             const lastCallback = getCallback(mapCallback, mapThisArgument, `${firstCallback}${restParameterString}`),
-                                restParameters = sourceCode.getText().slice(callback.end, parent.end);
+                                restParameters = sourceCode.getText().slice(callback.loc.end.column, parent.loc.end.column);
```
Comment (freaktechnik) [inline rules/from-map.js:79]: This should use `callback.range[1]` instead of `loc.end.column`. Same goes for all ranges. `range[0]` is the start, `range[1]` is the end. I believe the current approach only works because all unit tests only operate on the first line.

File: test/rules/from-map-ts.js [hunk 2]
```diff
@@ -0,0 +1,75 @@
...
+
+const ruleTester = new AvaRuleTester(test, {
+    parser: require.resolve('@typescript-eslint/parser'),
+    parserOptions: {
+        ecmaVersion: 2020,
+        sourceType: 'module'
+    }
+});
+
+ruleTester.run('from-map', rule, {
```
Comment (freaktechnik) [inline test/rules/from-map-ts.js:13]: I wonder if the actual rule tests should be shared with a helper module, so adding a test for the rule automatically checks for both parsers.
